In [1]:
python  functions
1.Assigned As a Value 
2. taken as input argument in another function
3. Defined inside another function
4.Return a functon as output from another function


SyntaxError: invalid decimal literal (127466375.py, line 2)

In [11]:
def abc():
    print('hi')

In [13]:
def xtz(f):
    f()

In [14]:
xyz(f = abc)

NameError: name 'xyz' is not defined

In [15]:
def xyz(f):
    f()

In [17]:
xyz(f=abc)

hi


In [18]:
def pqr():
    def qrp():
        print('hello')
    return qrp


In [20]:
x = pqr()
x

<function __main__.pqr.<locals>.qrp()>

In [21]:
x()

hello


In [22]:

# Annonymous Function - Lambda Expresssions
# Lambda inp_args : output (returned)

# Its always one-liner
# Always returns
# Input arguments ccan be multiple,optional,keyword,name,etc.
# Output can be simple/conditional/comprehemsion etc


In [24]:
doubler_L=lambda x : x*2
doubler_L

<function __main__.<lambda>(x)>

In [25]:
doubler_L(34)

68

In [27]:
oddeve = lambda x: 'Odd' if x%2 else 'Even'
oddeve(10000000000)

'Even'

In [28]:
# Scope of variables
## global
## local
## non local


In [29]:
x = 10

def abc():
    print(x)

abc()

10


In [35]:
x = 10

def abc():
    # global x
    x = 30
    x = 15
    def xyz():
        y = 28
        print('From xyz', x)
    xyz()
    print(y)


print(x)
abc()
print(x)

10
From xyz 15


NameError: name 'y' is not defined

In [39]:
x = 10

def abc():
    # global x
    x = 30
    x = 15
    def xyz():
        y = 28
        print('From xyz', x)
    xyz()
    print(y)


print(x)
pqr()
print(x)

10
10


In [41]:
pip install pandas

     -------------------------------------- 11.2/11.2 MB 289.6 kB/s eta 0:00:00
     ------------------------------------ 502.3/502.3 kB 470.0 kB/s eta 0:00:00
     ---------------------------------------- 14.8/14.8 MB 1.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\INDIA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [42]:
-m pip install --upgrade pip


SyntaxError: invalid syntax (294659197.py, line 1)

In [43]:
import pandas as p

In [1]:
!python -m pip install numpy



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\INDIA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy

In [3]:
import pandas

In [4]:
import my_file

40


In [5]:
my_file.abc()

Good messge


In [6]:
import keyword

In [7]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [8]:
import keyword as keyword
kw.kwlist

NameError: name 'kw' is not defined

In [9]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [10]:
from keyword import kwlsit,iskeyword
kwlst

ImportError: cannot import name 'kwlsit' from 'keyword' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\keyword.py)

In [11]:
from keyword import kwlsit, iskeyword
kwlist

ImportError: cannot import name 'kwlsit' from 'keyword' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\keyword.py)

In [12]:
from keyword import kwlistt,iskeyword
kwlist

ImportError: cannot import name 'kwlistt' from 'keyword' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\keyword.py)

In [13]:
from keyword import kwlist,iskeyword
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [14]:
import numpy

In [15]:
import pandas

In [16]:
import numpy as np

In [17]:
a = np.array([])
a

array([], dtype=float64)

In [18]:
b = np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [19]:
len(a)

0

In [20]:
len(b)

5

In [21]:
a.dtype

dtype('float64')

In [22]:
b.dtype

dtype('int32')

In [23]:
b.shape

(5,)

In [24]:
b.size

5

In [25]:
a.argmin

<function ndarray.argmin>

In [26]:
a.dinm

AttributeError: 'numpy.ndarray' object has no attribute 'dinm'

In [27]:
a.ndim

1

In [28]:
b.ndim

1

In [29]:
c = np.array([[2,3,4],[4,56,8],[5,3,2,]])
c

array([[ 2,  3,  4],
       [ 4, 56,  8],
       [ 5,  3,  2]])

In [30]:
c.shape

(3, 3)

In [32]:
c = np.array([[[2],[3],[4]],[[4],[56],[8]],[[5],[3],[2]]])
c

array([[[ 2],
        [ 3],
        [ 4]],

       [[ 4],
        [56],
        [ 8]],

       [[ 5],
        [ 3],
        [ 2]]])

In [33]:
c.shape

(3, 3, 1)

In [34]:
c.sum(axis=1)

array([[ 9],
       [68],
       [10]])

In [35]:
c.mean(axis=1)

array([[ 3.        ],
       [22.66666667],
       [ 3.33333333]])

In [36]:
c[0:2,-1]

array([[4],
       [8]])