In [1]:
2+3

5

In [2]:
import numpy

In [3]:
import pandas

In [4]:
import numpy as np

In [35]:
a = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])

In [8]:
b = np.array([[4,8,7],[3,1,5],[6,9,13]])


In [9]:
a

array([[ 8,  6,  5],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [10]:
a.shape

(4, 3)

In [11]:
b.shape

(3, 3)

In [17]:
c = np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])

In [13]:
c

array([[  4,  41],
       [  8,  81],
       [  7,  71],
       [  3,  31],
       [  1,  11],
       [  5,  51],
       [  6,  61],
       [  9,  91],
       [ 13, 131]])

In [14]:
c.shape

(9, 2)

In [18]:
c

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [19]:
c.shape

(3, 3, 2)

In [24]:
a[1,:]

array([9, 3, 5])

In [26]:
a[0:5:1,2]

array([ 5,  5, 17,  8])

In [28]:
a[:,2]

array([ 5,  5, 17,  8])

In [29]:
a[:,2].shape

(4,)

In [30]:
a[2:3]

array([[11, 15, 17]])

In [31]:
a[:,-1:]

array([[ 5],
       [ 5],
       [17],
       [ 8]])

In [32]:
a[:,-3:]

array([[ 8,  6,  5],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [36]:
a[:,-3:]

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [43]:
c[1:,1:,:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [44]:
a

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [45]:
a+5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [46]:
a[0]

array([3, 8, 4])

In [47]:
a[0] = 13

In [48]:
a

array([[13, 13, 13],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [49]:
d = ([2,3,4])

In [50]:
d

[2, 3, 4]

In [51]:
d[0] = 13

In [52]:
d

[13, 3, 4]

In [54]:
b

array([[ 4,  8,  7],
       [ 3,  1,  5],
       [ 6,  9, 13]])

In [55]:
a

array([[13, 13, 13],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [58]:
a[0,:] = [30,40,50]

In [59]:
a

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [68]:
a[:,1] = [500,400,300,100]

In [69]:
a

array([[ 30, 500,  50],
       [  5, 400,   9],
       [ 11, 300,  17],
       [ 19, 100,   8]])

In [70]:
a[:2,1:] = [[202,303],[404,708]]

In [71]:
a

array([[ 30, 202, 303],
       [  5, 404, 708],
       [ 11, 300,  17],
       [ 19, 100,   8]])

In [76]:
a[3,:] = [2,3,4,]

In [77]:
a

array([[ 30, 202, 303],
       [  2,   3,   4],
       [ 11, 300,  17],
       [  2,   3,   4]])

In [79]:
np.append(a,[[1,1,1]],axis = 0)

array([[ 30, 202, 303],
       [  2,   3,   4],
       [ 11, 300,  17],
       [  2,   3,   4],
       [  1,   1,   1]])

In [91]:
np.append(a,[[6],[7],[8],[9]],axis =1 )

array([[ 30, 202, 303,   6],
       [  2,   3,   4,   7],
       [ 11, 300,  17,   8],
       [  2,   3,   4,   9]])

In [98]:
np.delete(a,3,axis=0)

array([[ 30, 202, 303],
       [  2,   3,   4],
       [ 11, 300,  17]])

In [99]:
a.reshape(6,2)

array([[ 30, 202],
       [303,   2],
       [  3,   4],
       [ 11, 300],
       [ 17,   2],
       [  3,   4]])

In [100]:
a.dtype

dtype('int32')

In [103]:
a1 = np.array([3.,5.,3,7])
a1

array([3., 5., 3., 7.])

In [104]:
a1.dtype

dtype('float64')

In [106]:
a1.astype('uint16')

array([3, 5, 3, 7], dtype=uint16)

In [107]:
# Nutshell
## We create arrays
#1.np.array()
#2 np.ones()
#3 np.zeroes()
#4 np.arange()
#5 np.linespace()
#6 np.randit()


In [4]:
import numpy as np


In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
range(1,11,1)

range(1, 11)

In [13]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
np.random.randint(1,6,1)

array([2])

In [17]:
np.random.randint(1,6,[4,3,2])

array([[[3, 5],
        [3, 2],
        [4, 2]],

       [[4, 1],
        [1, 5],
        [4, 3]],

       [[1, 2],
        [5, 5],
        [3, 4]],

       [[2, 1],
        [4, 4],
        [2, 3]]])

In [19]:
np.random.seed(10)
np.random.randint(31,6000,[4,3],)

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [20]:
np.random.rand(3,4)

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [27]:
r = np.loadtxt('somedata.txt',dtype=str)
r

array(['hi', 'is', 'the', 'file', 'python.'], dtype='<U7')

In [33]:
r = np.loadtxt('moredatat.txt',dtype=int)
r

array([45, 56, 67, 44])

In [37]:
p= np.savetxt('new.txt',p,delimiter=',')
p

NameError: name 'p' is not defined

In [38]:
k = np.random.rand(2,3)
k


array([[0.54254437, 0.14217005, 0.37334076],
       [0.67413362, 0.44183317, 0.43401399]])

In [44]:
k = np.savetxt('new.txt',r,delimiter=' ')
k